### ISSUE TITLE
Adding `EXCLUDE` checks with GiST

### ISSUE THREAD

**Issue by mordechaim** [romeerez/orchid-orm#419]
I'm dealing with time ranges; with some research I discovered a special type of checks to ensure time ranges between rows don't overlap, using the `btree_gist` Postgres extension and this syntax:

```sql
ADD CONSTRAINT "overlap_exclude"
EXLUDE USING GIST (
    "room_id" with =,
    tstzrange("start", "end") with &&
)
```

I did not find Orchid to support this notation, I created a manual migration, but now I can't run any new generations (seemingly some validation finds a discrepancy with existing checks). I get this error:

```
error: relation "orchidtmpview10" does not exist
    at [redacted]\node_modules\pg\lib\client.js:535:17
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async performQuery$1 ([redacted]\node_modules\pqb\src\adapter.ts:188:12)
    at async <anonymous> ([redacted]\node_modules\orchid-orm\src\migrations\generate\generators\generators.utils.ts:51:13)
    at async Promise.all (index 9)
    at async compareSqlExpressions ([redacted]\questboard\node_modules\orchid-orm\src\migrations\generate\generators\generators.utils.ts:25:5)
    at async Promise.all (index 1)
    at async processTables ([redacted]\node_modules\orchid-orm\src\migrations\generate\generators\tables.generator.ts:131:3)
    at async composeMigration ([redacted]\node_modules\orchid-orm\src\migrations\generate\composeMigration.ts:52:9)
    at async generate ([redacted]\node_modules\orchid-orm\src\migrations\generate\generate.ts:113:21) {
  length: 113,
  severity: 'ERROR',
  code: '42P01',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'namespace.c',
  line: '434',
  routine: 'RangeVarGetRelidExtended'
}
```

GiST also allow adding range indexes for faster querying, like 

```sql
CREATE INDEX ON table USING GIST (
    tstzrange("start", "end")
)
```

Which would be nice to support.

**Comment by mordechaim** [comment]
Perhaps supporting `t.constraint()` with raw SQL in the same fashion as `t.check()` would be the most flexible.

**Comment by romeerez** [comment]
I thought there is support for raw SQL where possible, perhaps it's missing for some cases, I'll look into this.

While it's not possible to support even a single percent of existing extensions, it's definitely important to make sure it's still possible to shoehorn an extension on top of the OrchidORM.

**Comment by romeerez** [comment]
I'm going to support `EXCLUDE` a little bit later, and for now I'm pushing a fix that will simply ignore the manually created `EXCLUDE` constraint so your migrations won't fail because of it.

> GiST also allow adding range indexes for faster querying, like

You can create an index with a custom sql:

```ts
export class Table extends BaseTable {
  readonly table = 'table';

  columns = this.setColumns(
    (t) => ({
      // ...columns
    }),
    (t) => [
      t.index([{ expression: `tstzrange("start", "end")` }], {
        using: 'GIST',
      })
    ],
  );
}
```

But, this is seems to be excessive for `EXCLUDE` constraint, as it creates index automatically, you can play with EXPLAIN ANALYZE to ensure.

**Comment by mordechaim** [comment]
The error I'm experiencing is indeed not related to this, it's related to checks not being detected properly.

I'm stillt trying to make sense of this and create a reproduction.

**Comment by romeerez** [comment]
I published a feature for such `exclude` constraints, so now this is supported.

```sql
ADD CONSTRAINT "overlap_exclude"
EXLUDE USING GIST (
    "room_id" with =,
    tstzrange("start", "end") with &&
)
```

The above would translate to the following ORM syntax:

```ts
export class MyTable extends BaseTable {
    columns = this.setColumns(
    (t) => ({
      id: t.uuid().primaryKey(),
      roomId: t.integer(),
      startDate: t.timestamp(),
      endDate: t.timestamp(),
    }),
    (t) => [
      t.exclude([
        { column: 'roomId', with: '=' },
        { expression: `tstzrange("startDate", "endDate")`, with: '&&' },
      ]),
    ],
}
```

Plus, add `btree_gist` to the `extensions` of `createORM`.

**Comment by mordechaim** [comment]
This is amazing, thanks @romeerez

**Comment by mordechaim** [comment]
It seems to fail on snakerized column names.

The following table:

```ts

export class RoomTable extends BaseTable {
  readonly table = 'room';

  columns = this.setColumns(
    (t) => ({
      id: t.identity().primaryKey(),
      userId: t.integer().nullable(),
      start: t.timestamp(),
      end: t.timestamp(),
    }),
    (t) => [
      t.exclude(
        [
          {
            column: 'userId',
            with: '=',
          },
          {
            expression: 'tstzrange("start", "end")',
            with: '&&',
          },
        ],
        'room_start_end_overlap_exclude',
        {
          where: '("user_id" is not null)',
          using: 'GIST',
        }
      ),
    ]
  );
}

```

Causes this error:

```ts
Error: Failed to verify generated migration: some of database changes were not applied properly. This is a bug, please open an issue, attach the following migration code:

change(async (db) => {
  await db.createExtension('btree_gist');

  await db.createTable(
    'room',
    (t) => ({
      id: t.identity().primaryKey(),
      userId: t.integer().nullable(),
      start: t.timestamp(),
      end: t.timestamp(),
    }),
    (t) =>
      t.exclude(
        [
          {
            column: 'userId',
            with: '=',
          },
          {
            expression: 'tstzrange("start", "end")',
            with: '&&',
          },
        ],
        'room_start_end_overlap_exclude',
        {
          using: 'GIST',
          where: '("user_id" is not null)',
        },
      ),
  );
});

After applying:

change(async (db) => {
  await db.changeTable('room', (t) => ({
    ...t.drop(
      t.exclude(
        [
          {
            column: 'user_id',
            with: '=',
          },
          {
            expression: 'tstzrange(start, "end")',
            with: '&&',
          },
        ],
        'room_start_end_overlap_exclude',
        {
          using: 'gist',
          where: '(user_id IS NOT NULL)',
        },
      ),
    ),
    ...t.add(
      t.exclude(
        [
          {
            column: 'userId',
            with: '=',
          },
          {
            expression: 'tstzrange("start", "end")',
            with: '&&',
          },
        ],
        'room_start_end_overlap_exclude',
        {
          using: 'GIST',
          where: '("user_id" is not null)',
        },
      ),
    ),
  }));
});
```


Another issue, `where` requires parentheses, otherwise it produces broken sql.

**Comment by mordechaim** [comment]
Actually, even with `snakeCase: false` it still fails. Looks like some quoting issue, I don't know.


This table
```ts
export class RoomTable extends BaseTable {
  readonly table = 'room';

  columns = this.setColumns(
    (t) => ({
      id: t.identity().primaryKey(),
      user_id: t.integer().nullable(),
      start: t.timestamp(),
      end: t.timestamp(),
    }),
    (t) => [
      t.exclude(
        [
          {
            column: 'user_id',
            with: '=',
          },
          {
            expression: 'tstzrange("start", "end")',
            with: '&&',
          },
        ],
        'room_start_end_overlap_exclude',
        {
          where: '("user_id" is not null)',
          using: 'GIST',
        }
      ),
    ]
  );
}

```

Produces this error:

```ts
Error: Failed to verify generated migration: some of database changes were not applied properly. This is a bug, please open an issue, attach the following migration code:

change(async (db) => {
  await db.createExtension('btree_gist');

  await db.createTable(
    'room',
    (t) => ({
      id: t.identity().primaryKey(),
      user_id: t.integer().nullable(),
      start: t.timestamp(),
      end: t.timestamp(),
    }),
    (t) =>
      t.exclude(
        [
          {
            column: 'user_id',
            with: '=',
          },
          {
            expression: 'tstzrange("start", "end")',
            with: '&&',
          },
        ],
        'room_start_end_overlap_exclude',
        {
          using: 'GIST',
          where: '("user_id" is not null)',
        },
      ),
  );
});

After applying:

change(async (db) => {
  await db.changeTable('room', (t) => ({
    ...t.drop(
      t.exclude(
        [
          {
            column: 'user_id',
            with: '=',
          },
          {
            expression: 'tstzrange(start, "end")',
            with: '&&',
          },
        ],
        'room_start_end_overlap_exclude',
        {
          using: 'gist',
          where: '(user_id IS NOT NULL)',
        },
      ),
    ),
    ...t.add(
      t.exclude(
        [
          {
            column: 'user_id',
            with: '=',
          },
          {
            expression: 'tstzrange("start", "end")',
            with: '&&',
          },
        ],
        'room_start_end_overlap_exclude',
        {
          using: 'GIST',
          where: '("user_id" is not null)',
        },
      ),
    ),
  }));
});
```

**Comment by romeerez** [comment]
The bug here is because the db returns `gist` in lower case, while it's in caps case in the code, so you can try `GIST` -> `gist` in the code to make it work, until it's fixed.

**Comment by romeerez** [comment]
Fixed in the recent update.
